# global config
global:
  scrape_interval: 45s # Set the scrape interval to every 45 seconds. Default is every 1 minute.
  scrape_timeout: 30s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    origin_prometheus: mktxp

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
    - targets: ['promtail:9080']

  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']

  - job_name: 'blackbox'
    scrape_interval: 1s
    metrics_path: /probe
    params:
      module: [icmp_ttl5]  # use ICMP as the ping protocol
    static_configs:
      - targets:
        - 1.1.1.1
        - 8.8.8.8
        - 77.88.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
  
  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.78.240:9221  # Host 1 Proxmox VE with PVE exporter
    metrics_path: /pve
    params:
      module: [default]

  - job_name: 'adguard'
    static_configs:
      - targets: ['192.168.78.110:9618']